### ISSUE TITLE
Make pyramid pooling a possibility. 

### ISSUE THREAD

**Issue by Chriskamphuis** [Chriskamphuis/ISMI-Project#13]
See if we can use spatial pyramid pooling using the code in this repo: 

https://github.com/yhenon/keras-spp

Would really make the preprocessing better.

**Comment by jonasteuwen** [comment]
Be aware that this implementation is not 100% as in the SPP paper. Lasagne does seem to have a proper implementation, and I have seen a Tensorflow implementation floating around somewhere on GitHub (in the issues).

Also, be aware of the memory issues, if you go from smaller to large image, the GPU will reallocate memory.
